http:
  middlewares:
    security-headers:
      headers:
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        customResponseHeaders:
          X-XSS-Protection: '1; mode=block'
          X-Content-Type-Options: nosniff
          X-Frame-Options: DENY
          Referrer-Policy: strict-origin-when-cross-origin
          Permissions-Policy: geolocation=(), microphone=(), camera=()

    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 1m
